apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-05-24T18:36:22Z"
  generateName: hello-minikube-77b6f68484-
  labels:
    app: hello-minikube
    pod-template-hash: 77b6f68484
  name: hello-minikube-77b6f68484-48gv4
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: hello-minikube-77b6f68484
    uid: 9f20d8bc-7537-4445-a39e-8b845b487fb8
  resourceVersion: "681"
  uid: 629d1717-7f56-4e0e-ac84-bbd89a7b0223
spec:
  containers:
  - image: kicbase/echo-server:1.0
    imagePullPolicy: IfNotPresent
    name: echo-server
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hrs5x
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-hrs5x
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-05-24T18:36:22Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-05-24T18:36:25Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-05-24T18:36:25Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-05-24T18:36:22Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://1004e12dd4d77673ab802b626f308bdd899ff792eff8beb2aa9654e9bd064074
    image: kicbase/echo-server:1.0
    imageID: docker-pullable://kicbase/echo-server@sha256:127ac38a2bb9537b7f252addff209ea6801edcac8a92c8b1104dacd66a583ed6
    lastState: {}
    name: echo-server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-24T18:36:24Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 10.244.0.4
  podIPs:
  - ip: 10.244.0.4
  qosClass: BestEffort
  startTime: "2023-05-24T18:36:22Z"

